name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or the version of Node.js your project uses

      - name: Clean node_modules and package-lock
        run: |
          rm -rf node_modules package-lock.json
        working-directory: pythonProject

      - name: Install dependencies
        run: npm install --force
        working-directory: pythonProject

      - name: List files for debugging
        run: ls -la
        working-directory: pythonProject

      - name: List files in subdirectories for debugging
        run: find . -type f
        working-directory: pythonProject

      - name: Run Jest tests
        run: npm test
        working-directory: pythonProject

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: pythonProject

      - name: Build Docker image
        run: docker build -t snake_game:latest .
        working-directory: pythonProject/backend

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag snake_game:latest $DOCKER_USERNAME/snake_game:latest
          docker push $DOCKER_USERNAME/snake_game:latest
